#+TITLE: Spacemacs tangled user configuration
#+AUTHOR:  Colin Noel Bell
#+EMAIL:   col@baibell.org
#+STARTUP: headlines
#+STARTUP: nohideblocks
#+STARTUP: noindent
#+OPTIONS: toc:5 h:5
#+PROPERTY: header-args:emacs-lisp :comments link
#+HTML_HEAD_EXTRA: Spacemacs Configuration as pretty HTML. See <tt>~/.spacemacs.d/spacemacs.org</tt> for the actual configuration source.

* Introduction
#+begin_quote
Emacs outshines all other editing software in approximately the same
way that the noonday sun does the stars. It is not just bigger and
brighter; it simply makes everything else vanish.

-- Neal Stephenson, "[[http://www.cryptonomicon.com/beginning.html][In the Beginning was the Command Line]]"
#+end_quote

I've converted my Emacs configuration to an [[http://www.orgmode.org][org-mode]] file which
can be loaded using =(org-babel-load-file /path/to/file)=.

The original inspiration came from a blog post by [[http://sachachua.com/blog/2012/06/literate-programming-emacs-configuration-file/][Sacha Chua]]. To do this in Spacemacs I used [[https://www.reddit.com/r/emacs/comments/7ntc6p/spacemacs_configuration_in_a_structured_orgmode][this]].

Place the following code in your =~/.spacemacs.d/init.el= file.

** init.el

#+BEGIN_SRC emacs-lisp :tangle no
  (defun dotspacemacs/user-init ()
    ;; tangle without actually loading org
    (let ((src (concat dotspacemacs-directory "spacemacs.org"))
          (ui (concat dotspacemacs-directory "user-init.el"))
          (uc (concat dotspacemacs-directory "user-config.el")))
      (when (or (file-newer-than-file-p src ui) (file-newer-than-file-p src uc))
        (call-process
         (concat invocation-directory invocation-name)
         nil nil t
         "-q" "--batch" "--eval" "(require 'ob-tangle)"
         "--eval" (format "(org-babel-tangle-file \"%s\")" src)))
      (load-file ui)))

  (defun dotspacemacs/user-config ()
    (load-file (concat dotspacemacs-directory "user-config.el")))
#+END_SRC

* Editing warning

Place a warning in the generated .el files.

#+BEGIN_SRC emacs-lisp :tangle user-init.el
  ;;; -----------------------------------------------
  ;;; Do not edit this file, as it has been generated
  ;;; from an Orgmode file. If you do all changes will
  ;;; be lost when it is next generated on Emacs restart.
  ;;;
  ;;; Source: ~/.spacemacs.d/spacemacs.org
  ;;; -----------------------------------------------
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle user-config.el
  ;;; -----------------------------------------------
  ;;; Do not edit this file, as it has been generated
  ;;; from an Orgmode file. If you do all changes will
  ;;; be lost when it is next generated on Emacs restart.
  ;;;
  ;;; Source: ~/.spacemacs.d/spacemacs.org
  ;;; -----------------------------------------------
#+END_SRC

* Basic setup.
** Me, Myself I
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq user-mail-address "col@baibell.org")
  (setq user-full-name "Colin Bell")
#+END_SRC

** Look and Feel

Apply ligatures to Fira Code.

#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (defun my-correct-symbol-bounds (pretty-alist)
    "Prepend a TAB character to each symbol in this alist,
  this way compose-region called by prettify-symbols-mode
  will use the correct width of the symbols
  instead of the width measured by char-width."
    (mapcar (lambda (el)
              (setcdr el (string ?\t (cdr el)))
              el)
            pretty-alist))

  (defun my-ligature-list (ligatures codepoint-start)
    "Create an alist of strings to replace with
  codepoints starting from codepoint-start."
    (let ((codepoints (-iterate '1+ codepoint-start (length ligatures))))
      (-zip-pair ligatures codepoints)))

  (setq my-fira-code-ligatures
        (let* ((ligs '("www" "**" "***" "**/" "*>" "*/" "\\\\" "\\\\\\"
                       "{-" "[]" "::" ":::" ":=" "!!" "!=" "!==" "-}"
                       "--" "---" "-->" "->" "->>" "-<" "-<<" "-~"
                       "#{" "#[" "##" "###" "####" "#(" "#?" "#_" "#_("
                       ".-" ".=" ".." "..<" "..." "?=" "??" ";;" "/*"
                       "/**" "/=" "/==" "/>" "//" "///" "&&" "||" "||="
                       "|=" "|>" "^=" "$>" "++" "+++" "+>" "=:=" "=="
                       "===" "==>" "=>" "=>>" "<=" "=<<" "=/=" ">-" ">="
                       ">=>" ">>" ">>-" ">>=" ">>>" "<*" "<*>" "<|" "<|>"
                       "<$" "<$>" "<!--" "<-" "<--" "<->" "<+" "<+>" "<="
                       "<==" "<=>" "<=<" "<>" "<<" "<<-" "<<=" "<<<" "<~"
                       "<~~" "</" "</>" "~@" "~-" "~=" "~>" "~~" "~~>" "%%"
                       "x" ":" "+" "+" "*")))
          (my-correct-symbol-bounds (my-ligature-list ligs #Xe100))))

  (defun my-set-prog-ligatures ()
    "Add ligatures for programming modes"
    (setq prettify-symbols-alist
          (append my-fira-code-ligatures prettify-symbols-alist))
    (prettify-symbols-mode))

  (add-hook 'prog-mode-hook #'my-set-prog-ligatures)
#+END_SRC


Configure Solarized Theme.
#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (setq solarized-scale-org-headlines t)
  (setq solarized-use-variable-pitch t)
  (setq solarized-high-contrast-mode-line nil)
#+END_SRC

Show fill column indicator at pos 120.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq fill-column 120)
  (add-hook 'prog-mode-hook #'fci-mode)
#+END_SRC

Remove unnecessary clutter
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq use-file-dialog nil)
  (setq use-dialog-box nil)
  (with-eval-after-load 'spaceline-segments
     (spaceline-toggle-minor-modes))
  (setq-default display-line-numbers-width nil)
#+END_SRC

Auto-move mouse cursor away from text pointer
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (mouse-avoidance-mode 'exile)
#+END_SRC

*** Modeline.

Configure Doom modeline. This has to be set prior to the theme been loaded.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  ;; (setq doom-modeline-buffer-file-name-style 'relative-from-project)
  ;; (setq doom-modeline-icon t)
#+END_SRC

Fix Problems with scaling powerline in modeline.
  See https://github.com/syl20bnr/spacemacs/issues/8131.

#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (spacemacs/set-default-font dotspacemacs-default-font)
#+END_SRC

** General

  Allow paste into xterm etc.
#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (setq select-enable-primary t)
#+END_SRC

C-l first position to top.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq recenter-positions '(top middle bottom))
#+END_SRC

Keep Emacs maintained configuration separate
#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (setq custom-file (expand-file-name "custom.el" dotspacemacs-directory))
  (load custom-file)
#+END_SRC

Visually indicate Evil operations.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq evil-goggles-pulse 'display-graphic-p)
  (setq evil-goggles-async-duration nil)
  (setq evil-goggles-blocking-duration nil)
#+END_SRC

If saving a script file ensure that it is executable
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (add-hook 'after-save-hook
            #'executable-make-buffer-file-executable-if-script-p)
#+END_SRC

Save contents of scratch buffer on exit and restore on startup.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (use-package persistent-scratch
    :config
    (setq persistent-scratch-save-file
          (concat(file-name-as-directory spacemacs-cache-directory)
                 "persistent-scratch"))
    (persistent-scratch-setup-default))

#+END_SRC

Don't save duplicates in command history, search history etc.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq history-delete-duplicates t)
#+END_SRC

???

#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (setq exec-path-from-shell-check-startup-files nil)
#+END_SRC

* Major Modes
** Enacs Lisp
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (remove-hook 'emacs-lisp-mode-hook 'auto-compile-mode)
#+END_SRC

** Ruby

Configure Linting.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (use-package rubocop
    :ensure t
    :defer t
    :commands rubocop-mode
    :diminish rubocop-mode)
#+END_SRC

Alignment rules.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq ruby-align-chained-calls t)
#+END_SRC

** Elixir
Fixes problems with code reloading not working in Elixir/Phoenix. See http://spacemacs.org/doc/FAQ.html#orgheadline18

#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq create-lockfiles nil)
#+END_SRC

#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq alchemist-test-status-modeline t)
  (setq alchemist-test-display-compilation-output t)
  ;; (setq alchemist-mix-test-default-options "--trace")
  (setq flycheck-elixir-credo-strict t)
#+END_SRC

** Elm
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (use-package elm-mode
    :defer t
    :config
    (setq elm-format-on-save t)
    (setq elm-tags-on-save t)
    (setq elm-sort-imports-on-save t))
#+END_SRC
** Web Mode
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (defun cnb/web-mode-hook ()
    "Hooks for Web mode."
    (setq web-mode-markup-indent-offset 2)
    (setq web-mode-css-indent-offset 2)
    (setq web-mode-code-indent-offset 2))

  (add-hook 'web-mode-hook 'cnb/web-mode-hook t)

  (setq emmet-indentation 2)
#+END_SRC

** CSS Modes
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (defun cnb/scss-mode-hook ()
    "Hooks for SCSS mode."
    (setq css-indent-offset 2))

  (add-hook 'scss-mode-hook 'cnb/scss-mode-hook t)
#+END_SRC

** Config files
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (add-hook 'conf-mode-hook #'linum-mode)
#+END_SRC

** Dired

Configure dired listing.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq dired-listing-switches "-alhG --group-directories-first")
#+END_SRC

Extra font-lock rules for dired.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (diredfl-global-mode)
#+END_SRC

Allow editing of permissions in wdired.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq wdired-allow-to-change-permissions t)
#+END_SRC

** Org
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (with-eval-after-load 'org
    (require 'ob-tangle)
    (setq org-directory "~/Dropbox/org/")
    (setq org-agenda-files
          (list (concat org-directory "personal.org")
                (concat org-directory "kwela.org")
                (concat org-directory "notes.org")))
    (setq org-todo-keywords
          (quote ((sequence "TODO(t)" "STARTED(n)" "|" "DONE(d!/!)")
                  (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)" "PHONE"))))

    ;; Allow refiling to any agenda file.
    (setq org-refile-targets (quote ((nil :maxlevel . 9)
                                     (org-agenda-files :maxlevel . 9))))

    (setq org-capture-templates
          '(("t" "todo" entry (file+headline (concat org-directory "personal.org") "Tasks")
             "* TODO [#A] %?\nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n%a\n")))

    ;; Allow refile to create parent tasks with confirmation
    ;;(setq org-refile-allow-creating-parent-nodes (quote confirm))
    )

#+END_SRC

** Terminal

Allow Ctrl-A and CTRL-R to work in terminal.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (defun cnb/setup-term-mode ()
    (evil-local-set-key 'insert (kbd "C-a") 'cnb/send-C-a)
    (evil-local-set-key 'insert (kbd "C-r") 'cnb/send-C-r))

  (defun cnb/send-C-a ()
    (interactive)
    (term-send-raw-string "\C-a"))

  (defun cnb/send-C-r ()
    (interactive)
    (term-send-raw-string "\C-r"))

  (add-hook 'term-mode-hook #'cnb/setup-term-mode)
#+END_SRC
** Text
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (add-hook 'text-mode-hook #'turn-on-auto-fill)
#+END_SRC

** Foreman
Don't use Evil mode for Foreman, it breaks the menu.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (evil-set-initial-state 'foreman-mode 'emacs)
#+END_SRC

Set key seq to start Foreman.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (spacemacs/set-leader-keys "of" 'foreman)
#+END_SRC

* Utilities
** Visual Bookmarks
Next/Previous bookmark shortcuts
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (global-set-key (kbd "M-n") #'bm-next)
  (global-set-key (kbd "M-p") #'bm-previous)
#+END_SRC

** IBuffer
Hide empty filter groups
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq ibuffer-show-empty-filter-groups nil)
#+END_SRC

** Recent Files Mode
   #+BEGIN_SRC emacs-lisp :tangle user-config.el
     (with-eval-after-load 'recentf
       ;; Files to ignore in recent files.
       (add-to-list 'recentf-exclude "~$")
       (add-to-list 'recentf-exclude "tmp")
       (add-to-list 'recentf-exclude "/ssh:")
       (add-to-list 'recentf-exclude "/sudo:")
       (add-to-list 'recentf-exclude "TAGS")
       (add-to-list 'recentf-exclude "/\\.git/.*\\'")
       (add-to-list 'recentf-exclude recentf-save-file)

       ;; TODO: Check if this is still the case
       ;; Because .emacs.d is a symlink to dotfiles/emacs.d a file can have two
       ;; names so we also need to ignore the one in dotfiles.
       (add-to-list 'recentf-exclude (file-truename "~/dotfiles/emacs.d/elpa"))
       (add-to-list 'recentf-exclude
                    (file-truename "~/dotfiles/emacs.d/.cache/")))

   #+END_SRC

** Ivy/Swiper
  #+BEGIN_SRC emacs-lisp :tangle user-config.el
  (defun cnb/swiper-recenter (&rest args)
    "recenter display after swiper"
    (recenter))

  (advice-add 'swiper :after #'cnb/swiper-recenter)
  #+END_SRC

** Projectile
   Cache project files for performance.
   #+BEGIN_SRC emacs-lisp :tangle user-config.el
     (setq projectile-enable-caching t)
   #+END_SRC

   Spacemacs doesn't have a default key for showing a buffer list of just the current projects buffers.
   #+BEGIN_SRC emacs-lisp :tangle user-config.el
     (spacemacs/set-leader-keys "oi" 'projectile-ibuffer)
   #+END_SRC
** Rainbow Mode
Colourize colour names in programming modes.
  #+BEGIN_SRC emacs-lisp :tangle user-config.el
  (setq rainbow-html-colors t)
  (setq rainbow-x-colors t)
  (add-hook 'prog-mode-hook #'rainbow-mode)
  #+END_SRC

** Source Control

Show Magit status in a large window.
#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (setq-default git-magit-status-fullscreen t)
#+END_SRC

Disable Evil for Magit status buffer.
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (evil-set-initial-state 'magit-status-mode 'emacs)
#+END_SRC

Show projects TODOs in Magit status buffer.
#+BEGIN_SRC emacs-lisp :tangle user-init.el
  (with-eval-after-load 'magit-mode
    (magit-todos-mode))
#+END_SRC

** EditorConfig
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (use-package editorconfig
    :defer t
    :init (add-to-list 'auto-mode-alist '("\\.editorconfig" . conf-unix-mode)))
#+END_SRC

** Show current function
#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (which-function-mode)
  ;; (set-face-attribute 'which-func nil
  ;;                     :foreground (face-foreground 'font-lock-function-name-face))
  ;;
  ;; (setq-default header-line-format
  ;;               '((which-func-mode ("" which-func-format " "))))
#+END_SRC

** Time

Set timezones for helm-world-time.

#+BEGIN_SRC emacs-lisp :tangle user-config.el
  (require 'time)
  (setq display-time-world-list '(("Australia/Sydney" "Sydney")
                                   ("Australia/Perth" "Perth")
                                   ("America/Los_Angeles" "Los Angeles")
                                   ("America/New_York" "New York")
                                   ("Asia/Shanghai" "China")
                                   ("Europe/Belfast" "Belfast")))
#+END_SRC

* CLEANUP

#+BEGIN_SRC emacs-lisp :tangle user-config.el

  ;;===============================================
  ;; Work around for https://github.com/syl20bnr/spacemacs/issues/10410
  ;;===============================================
  (defun kill-minibuffer ()
    (interactive)
    (when (windowp (active-minibuffer-window))
      (evil-ex-search-exit)))
  (add-hook 'mouse-leave-buffer-hook #'kill-minibuffer)

  ;; (setq imenu-list-auto-resize nil)

  ;; Let me right-click in terminal to show terminal menu.
  (xterm-mouse-mode -1)

  (setq-default
   sentence-end-double-space nil

   ;; Use a visible bell instead of a beep.
   visible-bell t

   ;; Always start a new tags list.
   tags-add-tables nil

   ;; When opening files follow all symbolic links.
   find-file-visit-truename t

   ;; I've got some TAGS files that are nearly 20MB in size.
   large-file-warning-threshold 20000000

   imenu-auto-rescan t


   ;;browse-url-browser-function 'browse-url-firefox
   browse-url-browser-function 'browse-url-generic
   browse-url-generic-program "chromium-browser"
   )


  (setq kill-ring-max 500)

  (setq evil-want-fine-undo "Yes")

  ;; (global-set-key (kbd "TAB") #'company-indent-or-complete-common)

  ;; My common mistakes.
  (define-abbrev-table
    'global-abbrev-table '(("teh" "the" nil 0)
                           ("tehy" "they" nil 0)
                           ("yuo" "you" nil 0)
                           ("yuor" "your" nil 0)))
  (setq-default abbrev-mode t)

  ;; Seems to be needed for evil to work with system clipboard
  (fset 'evil-visual-update-x-selection 'ignore)

#+END_SRC
