;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Editing%20warning][Editing warning:1]]
;;; -----------------------------------------------
;;; Do not edit this file, as it has been generated
;;; from an Orgmode file. If you do all changes will
;;; be lost when it is next generated on Emacs restart.
;;;
;;; Source: ~/.spacemacs.d/spacemacs.org
;;; -----------------------------------------------
;; Editing warning:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Themes][Themes:1]]
(setq solarized-distinct-fringe-background nil)
(setq solarized-scale-org-headlines nil)
(setq solarized-use-variable-pitch nil)
(setq solarized-high-contrast-mode-line nil)
;; Themes:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Basic%20setup.][Basic setup.:1]]
(setq select-enable-primary t)
;; Basic setup.:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Basic%20setup.][Basic setup.:5]]
(spacemacs/set-default-font dotspacemacs-default-font)
;; Basic setup.:5 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*???][???:1]]
(setq exec-path-from-shell-check-startup-files nil)
;; ???:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Keep%20Emacs%20maintained%20configuration%20separate][Keep Emacs maintained configuration separate:1]]
(setq custom-file (expand-file-name "custom.el" dotspacemacs-directory))
(load custom-file)
;; Keep Emacs maintained configuration separate:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Source%20Control][Source Control:1]]
(setq-default git-magit-status-fullscreen t)
;; Source Control:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Source%20Control][Source Control:2]]
(with-eval-after-load 'magit-mode
  (magit-todos-mode))
;; Source Control:2 ends here
