;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Editing%20warning][Editing warning:1]]
;;; -----------------------------------------------
;;; Do not edit this file, as it has been generated
;;; from an Orgmode file. If you do all changes will
;;; be lost when it is next generated on Emacs restart.
;;;
;;; Source: ~/.spacemacs.d/spacemacs.org
;;; -----------------------------------------------
;; Editing warning:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Themes][Themes:1]]
(setq solarized-scale-org-headlines t)
(setq solarized-use-variable-pitch t)
(setq solarized-high-contrast-mode-line nil)
;; Themes:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Modeline.][Modeline.:2]]
(spacemacs/set-default-font dotspacemacs-default-font)
;; Modeline.:2 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Customize][Customize:1]]
(setq custom-file (expand-file-name "custom.el" dotspacemacs-directory))
(load custom-file)
;; Customize:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Mark,%20Kill,%20Paste%20And%20Undo][Mark, Kill, Paste And Undo:1]]
(setq select-enable-primary t)
;; Mark, Kill, Paste And Undo:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Gen][Gen:2]]
(setq exec-path-from-shell-check-startup-files nil)
;; Gen:2 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Source%20Control][Source Control:1]]
(setq-default git-magit-status-fullscreen t)
;; Source Control:1 ends here

;; [[file:~/dotfiles/spacemacs.d/spacemacs.org::*Source%20Control][Source Control:3]]
(with-eval-after-load 'magit-mode
  (magit-todos-mode))
;; Source Control:3 ends here
