;; [[file:~/.spacemacs.d/spacemacs.org::*Editing%20warning][Editing warning:1]]
;;; -----------------------------------------------
;;; Do not edit this file, as it has been generated
;;; from an Orgmode file. If you do all changes will
;;; be lost when it is next generated on Emacs restart.
;;;
;;; Source: ~/.spacemacs.d/spacemacs.org
;;; -----------------------------------------------
;; Editing warning:1 ends here

;; [[file:~/.spacemacs.d/spacemacs.org::*CLEANUP][CLEANUP:1]]
;; These have to be set prior to the theme been loaded.
(setq solarized-distinct-fringe-background nil)
(setq solarized-scale-org-headlines nil)
(setq solarized-use-variable-pitch nil)
(setq solarized-high-contrast-mode-line nil)

(setq exec-path-from-shell-check-startup-files nil)

;;==============================================
;; source control configuration
;;==============================================
;; (global-git-commit-mode t)
(setq-default git-magit-status-fullscreen t)
(setq magit-repository-directories
  '(("~/dotfiles/" . 0)
    ("~/src/"      . 1)))

(with-eval-after-load 'magit-mode
  (magit-todos-mode))

;;==============================================
;; Keep Emacs maintained configuration separate
;;==============================================
(setq custom-file (expand-file-name "custom.el" dotspacemacs-directory))
(load custom-file)

;; TODO: Workaround for https://github.com/syl20bnr/spacemacs/issues/8131
(spacemacs/set-default-font dotspacemacs-default-font)

;; Allow paste into xterm etc.
(setq select-enable-primary t)
;; CLEANUP:1 ends here
